'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'
import AuthForm from '@/components/ui/AuthForm'
import { BookOpen, Brain, BarChart3, Zap } from 'lucide-react'

export default function HomePage() {
  const { user, loading } = useAuth()
  const router = useRouter()

  useEffect(() => {
    if (!loading && user) router.push('/dashboard')
  }, [user, loading, router])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="loading-spinner w-8 h-8" />
      </div>
    )
  }

  if (user) return null

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50/30 to-indigo-50/40">
      <div className="max-w-6xl mx-auto px-4 py-8 lg:py-16">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-1.5 rounded-full text-sm font-medium mb-4">
            <Zap size={14} />
            AI-Powered Study Assistant
          </div>
          <h1 className="text-4xl lg:text-5xl font-bold text-foreground tracking-tight mb-4">
            Study Smarter, Not Harder
          </h1>
          <p className="text-lg text-muted-foreground max-w-xl mx-auto">
            Let AI create your study schedule, detect weak topics, generate quizzes, and keep you on track.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-12 items-start">
          {/* Features */}
          <div className="space-y-6">
            <div className="grid grid-cols-2 gap-4">
              {[
                { icon: Brain, title: 'AI Study Plans', desc: 'Personalized schedules generated by AI based on your exams and goals' },
                { icon: BarChart3, title: 'Analytics', desc: 'Track progress with charts, streaks, and subject distribution' },
                { icon: BookOpen, title: 'Smart Quizzes', desc: 'AI-generated MCQs and flashcards from your study notes' },
                { icon: Zap, title: 'Weak Topic Detection', desc: 'AI identifies and flags topics that need more attention' },
              ].map(({ icon: Icon, title, desc }) => (
                <div key={title} className="card p-4">
                  <div className="w-8 h-8 bg-primary/10 rounded-lg flex items-center justify-center mb-3">
                    <Icon size={16} className="text-primary" />
                  </div>
                  <h3 className="font-semibold text-sm text-foreground mb-1">{title}</h3>
                  <p className="text-xs text-muted-foreground leading-relaxed">{desc}</p>
                </div>
              ))}
            </div>

            <div className="card p-5 bg-primary/5 border-primary/20">
              <p className="text-sm font-medium text-foreground mb-2">Tech Stack</p>
              <div className="flex flex-wrap gap-2">
                {['Next.js 14', 'Firebase Auth', 'Firestore', 'Tailwind CSS', 'Gemini AI', 'Recharts'].map(t => (
                  <span key={t} className="badge bg-white border border-border text-foreground text-xs">{t}</span>
                ))}
              </div>
            </div>
          </div>

          {/* Auth Form */}
          <AuthForm />
        </div>
      </div>
    </div>
  )
}
